server:
  port: 80

spring:
  application:
    name: consumer #微服务的applicationName。需要注意这个不是项目启动路径

#ribbon 负载均衡需要进行 eureka配置
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: consumer-dept-80 #自定义微服务实例名称信息,微服务名称不能重复，是唯一的。使用ribbon做轮询的时候这个不能重复，不然就是一个实例了。
    prefer-ip-address: true #访问路径可以显示ip地址信息，window电脑如果不配置的话那么就会显示电脑名称

#info信息
info:
  app.name: springcloud-demo
  company.name: floatpoint-tec
  build.artifactId: $project.artifactId$
  build.version: $project.version$

